name: "Upload to DefectDojo"
description: "Send scan results to DefectDojo"
runs:
  using: "composite"
  steps:
    - name: Upload Semgrep results
      run: |
        curl -X POST "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/" \
        -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
        -F "scan_type=Semgrep JSON Report" \
        -F "file=@semgrep-results.json"

    - name: Upload Trivy SCA results
      run: |
        curl -X POST "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/" \
        -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
        -F "scan_type=Trivy JSON Report" \
        -F "file=@trivy-sca-results.json"

    - name: Upload Container Scan results
      run: |
        curl -X POST "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/" \
        -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
        -F "scan_type=Trivy JSON Report" \
        -F "file=@trivy-container-results.json"
