name: "DAST (OWASP ZAP Baseline)"
description: "Run a lightweight ZAP baseline scan against a target URL"
inputs:
  target-url:
    description: "Target base URL (e.g. https://dev.example.com)"
    required: true
runs:
  using: "composite"
  steps:
    - name: Run ZAP Baseline (Docker)
      shell: bash
      run: |
        set -e
        docker pull owasp/zap2docker-stable:2.14.0
        docker run --rm -t owasp/zap2docker-stable:2.14.0 zap-baseline.py \
          -t "${{ inputs.target-url }}" -r zap-baseline-report.html -J zap-baseline.json || true
    - name: Upload ZAP report
      uses: actions/upload-artifact@v4
      with:
        name: zap-baseline
        path: |
          zap-baseline-report.html
          zap-baseline.json
