name: "Gitleaks Secret Scan"
description: "Scan for secrets using Gitleaks"
runs:
  using: "composite"
  steps:
    - name: Install Gitleaks (pinned)
      shell: bash
      run: |
        set -e
        VER=8.18.4
        curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v${VER}/gitleaks_${VER}_linux_x64.tar.gz \
          | tar -xz
        sudo mv gitleaks /usr/local/bin/
        gitleaks version
    - name: Run Gitleaks
      shell: bash
      run: |
        set -e
        if [ -f ".gitleaks.toml" ]; then
          gitleaks detect --source . --config .gitleaks.toml --report-format json --report-path gitleaks-results.json || true
        else
          gitleaks detect --source . --report-format json --report-path gitleaks-results.json || true
        fi
        # Fail if any leaks
        python3 - <<'PY'
        import json, sys
        try:
          data = json.load(open("gitleaks-results.json"))
        except Exception:
          print("No gitleaks report found; treating as no findings.")
          sys.exit(0)
        findings = data if isinstance(data,list) else data.get("findings") or data.get("Leaks") or []
        if findings:
          print(f"Gitleaks found {len(findings)} potential secrets; failing.")
          sys.exit(2)
        print("No secrets found.")
        PY
    - name: Upload Gitleaks results
      uses: actions/upload-artifact@v4
      with:
        name: gitleaks-results
        path: gitleaks-results.json
