name: "Trivy Container Scan"
description: "Scan container images for vulnerabilities"
runs:
  using: "composite"
  steps:
    - name: Scan Docker image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ inputs.image }}
        format: json
        output: trivy-container-results.json

    - name: Upload container scan results
      uses: actions/upload-artifact@v4
      with:
        name: trivy-container-results
        path: trivy-container-results.json
